name: Koolo Build CI
on:
  push:
  pull_request:
  release:

jobs:
  build:
    name: "Build Koolo binary"
    runs-on: windows-2022
    steps:
      - name: "Install CMake"
        run: |
          choco install cmake 7zip.install wget opencv --version=4.7.0
      - name: "Install MinGW"
        run: |
          wget -nv https://download.qt.io/development_releases/prebuilt/mingw_64/x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z
          7z x -oC: x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z
          "C:\mingw64\bin" >> $env:GITHUB_PATH
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Setup Go"
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
#      - name: "Building OpenCV"
#        run: |
#          go mod vendor
#          .\vendor\gocv.io\x\gocv\win_build_opencv.cmd static
      - name: "Building Koolo artifacts"
        run: |
          .\build.bat

#      - name: "Archive"
#        uses: actions/upload-artifact@v2
#        with:
#          name: koolo
#          path: koolo.exe

